apiVersion: v1
kind: Template
metadata:
  name: openstack-cassandra-poc
  annotations:
    description: Cassandra  cqlsh deploy
    tags: logs,poc,openstack,cassandra

parameters:
- name: SOURCE_REPOSITORY_URL
  description: URL of the Git repository Dockerfile
  required: true
  value: https://github.com/keedio/openstack-operations-poc.git
- name: OBJECT_NAME_PREFIX
  description: Name prefix for each object created
  required: true
  value: cassandra-openstack-poc

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: ${OBJECT_NAME_PREFIX}
      spec:
        containers:
        - name: cassandra-cql
          image: ${OBJECT_NAME_PREFIX}
          command:
          - "/opt/apache-cassandra/bin/docker-entrypoint.sh"
          - "--cluster_name=openstack-cluster"
          env:
            - name: PEER_DISCOVERY_SERVICE
              value: cassandra-peers
          ports:
          - name: cql-port
            containerPort: 9042
          - name: thift-port
            containerPort: 9160
          - name:  intra-node
            containerPort: 7000
          - name: tls-intra
            containerPort: 7001    
        volumeMounts:
          - name: cassandra-data
            mountPath: "/var/lib/cassandra/data"
        volumes:
        - name: cassandra-data          
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - cassandra-cql
        from:
          kind: ImageStream
          name: ${OBJECT_NAME_PREFIX}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: cassandra-peers
    name: cassandra-peers
  spec:
    clusterIP: None
    ports:
      - port: 7000
        name: intra-node
      - port: 7001
        name: tls-intra
    selector:
      app: ${OBJECT_NAME_PREFIX}      
- apiVersion: v1
  kind: Service
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    ports:
    - port: 9042
      name: cql-port
    selector:
      app: ${OBJECT_NAME_PREFIX}      